kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mc-claim-lel
  namespace: breakfast-manager
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: breakfast-manager
  name: mck8s
spec:
  replicas: 1
  selector:
    matchLabels:
      service: mck8s
  template:
    metadata:
      namespace: breakfast-manager
      labels:
        service: mck8s
    spec:
      volumes:
        - name: mc-volume
          persistentVolumeClaim:
            claimName: mc-claim-lel
      containers:
        - name: mck8s
          image: itzg/minecraft-server:java8
          ports:
            - containerPort: 25565
              protocol: TCP
          volumeMounts:
            - name: mc-volume
              mountPath: /data
          env:
            - name: EULA
              value: "TRUE"
            - name: TYPE
              value: "FORGE"
            - name: VERSION
              value: "1.16.5"
            - name: MODS
              value: "https://media.forgecdn.net/files/3459/903/CBMultipart-1.16.5-3.0.2.120-universal.jar,https://media.forgecdn.net/files/3276/638/Scorge-3.1.3.jar,https://media.forgecdn.net/files/3456/69/CodeChickenLib-1.16.5-4.0.3.434-universal.jar,https://media.forgecdn.net/files/3407/713/ProjectRed-1.16.5-4.10.0-core.jar,https://media.forgecdn.net/files/3407/716/ProjectRed-1.16.5-4.10.0-exploration.jar,https://media.forgecdn.net/files/3407/718/ProjectRed-1.16.5-4.10.0-transmission.jar,https://media.forgecdn.net/files/3407/714/ProjectRed-1.16.5-4.10.0-integration.jar,https://media.forgecdn.net/files/3407/715/ProjectRed-1.16.5-4.10.0-illumination.jar,https://media.forgecdn.net/files/3480/853/jei-1.16.5-7.7.1.122.jar,https://media.forgecdn.net/files/3419/412/create-mc1.16.5_v0.3.2d.jar,https://media.forgecdn.net/files/3482/903/TConstruct-1.16.5-3.1.3.271.jar,https://media.forgecdn.net/files/3439/180/Mantle-1.16.5-1.6.123.jar,https://media.forgecdn.net/files/3459/739/flywheel-1.16-0.2.4.jar"
            - name: ONLINE_MODE
              value: "FALSE"
            - name: SERVER_NAME
              value: "GarticCircleMCServer"
            - name: MOTD
              value: "GarticCircleServer Penis 8===D"
            - name: MEMORY
              value: "3G"
          imagePullPolicy: IfNotPresent
---
kind: Service
apiVersion: v1
metadata:
  name: mck8s
spec:
  type: NodePort
  selector:
    service: mck8s
  ports:
    - protocol: TCP
      port: 25565
      targetPort: 25565
      nodePort: 32222
